import Head from "next/head"
import Link from "next/link"
import useAuth from "../hooks/useAuth"
import {AiOutlineCheck} from "react-icons/ai"
import Table from "./Table"
import {useState} from "react"
const Plans = () => {
    const {logout} = useAuth()
    const [selectedPlan, setSelectedPlan] = useState<number>(1)
    const [isBillingLoading, setIsBillingLoading] = useState(false)
    console.log(selectedPlan);
    const handleLogout = () =>{
      localStorage.removeItem("session")
      logout()

    }
    
  return (
    <div className="">
        <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="border-b border-white/10 bg-[#141414]">
        <Link href="/">
        <img src="https://rb.gy/ulxxee" width={100} height={100} className="cursor-pointer object-contain" />
        </Link>
        <button className="text-lg font-medium hover:underline" onClick={()=>handleLogout()}>Sign Out</button>
      </header>
      <main className="pt-28 px-5 mx-auto max-w-5xl pb-12 transition-all md:px-10">
        <h1 className="mb-3 font-medium text-3xl">Choose the plan that's right for you</h1>
        <ul>
          <li className="flex items-center gap-x-2 text-lg">
          <AiOutlineCheck className="w-7 h-7 text-[#e50914]" />
          Watch all you want. Ad-free
          </li>
           <li className="flex items-center gap-x-2 text-lg">
          <AiOutlineCheck className="w-7 h-7 text-[#e50914]" />
          Recommendations just for you
          </li>
           <li className="flex items-center gap-x-2 text-lg">
          <AiOutlineCheck className="w-7 h-7 text-[#e50914]" />
          Cancle your plan any time
          </li>
        </ul>
        <div className="flex flex-col mt-4 space-y-4">
          <div className="flex w-full items-center self-end justify-end md:w-[60%]">
            <div className={`planBox ${selectedPlan === 3 ? "opacity-100": "opacity-60"}`}
            onClick={()=>setSelectedPlan(3)}>Basic</div>
            <div className={`planBox ${selectedPlan === 2 ? "opacity-100": "opacity-60"}`}
            onClick={()=>setSelectedPlan(2)}>Standard</div>
            <div className={`planBox ${selectedPlan === 1 ? "opacity-100": "opacity-60"}`}
            onClick={()=>setSelectedPlan(1)}>Premium</div>
          </div>
          <Table selectedPlan={selectedPlan} />
          <button className={`bg-[#e50914] mx-auto w-11/12 rounded py-4
           text-xl shadow md:w-[420px] hover:bg-[#f6121d] ${isBillingLoading && "opacity-60"}`} disabled={isBillingLoading}>Subscribe</button>
        </div>
      </main>
    </div>
  )
}

export default Plans